### ISSUE TITLE
The triplet loss curve on Market1501 was strange

### ISSUE THREAD

**Issue by jianghaojun** [dongb5/AdversarialBinaryCoding4ReID#1]
I set the parameter to the values which were mentioned in your paper. And I ran your code to train the model on Market1501 and I got a strange triplet loss curve(iteration = 16000, hash_bit = 2048). 
![image](https://user-images.githubusercontent.com/30039000/41024361-9bd97516-69a1-11e8-9c6e-22d27c2a4bf1.png)
There is a significant oscillation on the curve. Obiviously, it is quite different from the your curves. I didn't change the code except the parameter. And I am sure that the parameters were as same as yours.  
The loss of discriminator and the loss of generator is just like the curves you posted on the github.
![image](https://user-images.githubusercontent.com/30039000/41024679-7708fcf6-69a2-11e8-9ac5-dc7bcfa5e766.png)

I can't figure out what is wrong. Could you please give me some advice.

**Comment by dongb5** [comment]
Sorry for the late reply. For better visualization in small figures in the paper, we actually average the triplet losses every 100 iterations due to the too many iterations. By doing this, the curves in small figures are more clear and easy to watch.
